site_name: FCP Development Guide
site_url: https://defra.github.io/ffc-development-guide/
theme: 
  name: material
  logo: img/favicon.png
  favicon: img/favicon.ico
  palette:
    primary: black
repo_url: https://github.com/DEFRA/ffc-development-guide
remote_branch: gh-pages
nav:
  - Home: index.md
  - Getting Started: 
    - Understand the Platform: getting-started/platform.md
    - Understand CI/CD approach: getting-started/cicd.md
    - Arrange access to resources: getting-started/arrange-access.md
  - Setup your local development environment: 
    - Overview: local-development-setup/index.md
    - Windows:
      - Install Windows Subsystem for Linux (WSL): local-development-setup/install-wsl.md
      - Update WSL configuration: local-development-setup/wsl.md
      - Add user to sudoers file: local-development-setup/setup-sudoers.md
    - Mac:
      - Setup command line tools: local-development-setup/setup-macos-command-line-tools.md
      - Mac setup Scripts: local-development-setup/mac-setup-scripts.md
    - Common:
      - Install Docker Desktop: local-development-setup/install-docker-desktop.md
      - Install Visual Studio Code: local-development-setup/install-vs-code.md
      - Install neostandard: local-development-setup/install-neostandard.md
      - Install Node Version Manager (NVM): local-development-setup/install-node-version-manager.md
      - Install .NET SDK: local-development-setup/install-dotnet-sdk.md
      - Install SonarQube: local-development-setup/install-sonarqube.md
      - Install Detect Secrets: local-development-setup/install-detect-secrets.md
      - Install kubectl: local-development-setup/install-kubectl.md
      - Install kubelogin: local-development-setup/install-kubelogin.md
      - Install Helm: local-development-setup/install-helm.md
      - Install Azure CLI: local-development-setup/install-azure-cli.md
      - Install Snyk CLI: local-development-setup/install-snyk.md
      - Install GitHub CLI: local-development-setup/install-github.md
      - Install OpenVPN: local-development-setup/install-openvpn.md
      - Setup commit signing: local-development-setup/sign-commits.md
  - Create a new service:
      - Choose a technology: create-a-new-service/choose-a-technology.md
      - Create a source code repository: create-a-new-service/github.md
      - Repository conventions: create-a-new-service/conventions.md
      - Setup a Jenkins CI pipeline: create-a-new-service/jenkins.md
      - Setup an Azure DevOps CD pipeline: create-a-new-service/ado.md
      - Deploy a service: create-a-new-service/deploy.md
  - Development patterns:
    - Containers: development-patterns/containers.md
    - Helm charts: development-patterns/helm-charts.md
    - Health probes: development-patterns/probes.md
    - Identity: development-patterns/identity.md
    - Configuration and secrets: development-patterns/configuration.md
    - Events and messages: development-patterns/events-and-messages.md
    - Storage: development-patterns/storage.md
    - Databases: development-patterns/databases.md
    - Caching: development-patterns/cache.md
    - Logging: development-patterns/logging.md
    - Authentication:
      - Defra Identity: development-patterns/authentication/defra-identity.md
      - Entra: development-patterns/authentication/entra.md
    - Analytics: development-patterns/analytics.md
    - Git secrets: development-patterns/git-secrets.md
    - Security: development-patterns/security.md
    - Shared assets: development-patterns/shared-assets.md
    - Version control: development-patterns/version-control.md
    - Documentation: development-patterns/documentation.md
    - Code review: development-patterns/code-review.md
    - Release notes: development-patterns/release-notes.md
  - Testing:
    - Unit: testing/unit.md
    - Integration: testing/integration.md
    - Contract: testing/contract.md
    - Performance: testing/performance.md
    - Security: testing/security.md
    - Accessibility: testing/accessibility.md
    - Compatibility: testing/compatibility.md
    - Code analysis: testing/code-analysis.md
    - Acceptance: testing/acceptance.md
