site_name: FCP Development Guide
site_url: https://defra.github.io/ffc-development-guide/
theme: material
repo_url: https://github.com/DEFRA/ffc-development-guide
remote_branch: gh-pages
nav:
  - Home: index.md
  - Getting Started: 
    - Understand the Platform: getting-started/platform.md
    - Understand CI/CD approach: getting-started/cicd.md
    - Arrange access to resources: getting-started/arrange-access.md
  - Setup your local development environment: 
    - Overview: local-development-setup/index.md
    - Windows:
      - Install Windows Subsystem for Linux (WSL): local-development-setup/install-wsl.md
      - Mount windows drives in WSL: local-development-setup/mount-windows-drives-in-wsl.md
      - Add user to sudoers file: local-development-setup/setup-sudoers.md
    - macOs:
      - Setup command line tools: local-development-setup/setup-macos-command-line-tools.md
    - Common:
      - Install Docker Desktop: local-development-setup/install-docker-desktop.md
      - Install Visual Studio Code: local-development-setup/install-vs-code.md
      - Install StandardJs: local-development-setup/install-standard-js.md
      - Install SonarLint: local-development-setup/install-sonarlint.md
      - Setup commit signing: local-development-setup/setup-commit-signing.md
      - Install Docker Compose: local-development-setup/install-docker-compose.md
      - Install Detect Secrets: local-development-setup/install-detect-secrets.md
      - Install Node Version Manager (NVM): local-development-setup/install-node-version-manager.md
      - Install .NET SDK: local-development-setup/install-dotnet-sdk.md
      - Install kubectl: local-development-setup/install-kubectl.md
      - Install Helm: local-development-setup/install-helm.md
      - Install Azure CLI: local-development-setup/install-azure-cli.md
      - Install Snyk CLI: local-development-setup/install-snyk.md
      - Install GitHub CLI: local-development-setup/install-github.md
      - Install OpenVPN: local-development-setup/install-openvpn.md
  - Create a new service:
      - Choose a technology: create-a-new-service/choose-a-technology.md
      - Create a source code repository: create-a-new-service/github.md
      - Setup a Jenkins CI pipeline: create-a-new-service/jenkins.md
      - Setup an Azure DevOps CD pipeline: create-a-new-service/azure-devops.md
  - Archive content:
      - Standards: archive/standards/index.md
      - Guides: archive/guides/index.md
